#Find the condition of all dataitems of the components of each device and their timestamp
PREFIX mmd: <http://example.org/mmd/mazakmachinedata#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX ssn: <http://purl.oclc.org/NET/ssnx/ssn>
PREFIX sem: <http://semanticweb.cs.vu.nl/2009/11/sem/>
PREFIX saref: <https://w3id.org/c>
SELECT ?device ?component ?dataitem ?timestamp ?condition
WHERE
{
    ?device saref:hasName ?name;
            ssn:hasPart ?component.
    ?component mmd:hasDataItem ?dataitem.
    ?dataitem mmd:hasCondition ?condition;
               sem:hasTimestamp ?timestamp.
}  
